button.js: use add_child() instead of add_actor()
add_actor() has been removed in GNOME shell 46

See https://gjs.guide/extensions/upgrading/gnome-shell-46.html#gjs

Fixes the following error:

Extension argos@pew.worldwidemann.com: TypeError: Utilities.getActor(...).add_actor is not a function

Stack trace:
  _init@file:///home/mwilck/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:36:30
  ButtonBox@resource:///org/gnome/shell/ui/panelMenu.js:12:1
  PanelMenuButton@resource:///org/gnome/shell/ui/panelMenu.js:97:4
  ArgosButton@file:///home/mwilck/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:26:1
  addButtons@file:///home/mwilck/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/extension.js:103:18
  enable@file:///home/mwilck/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/extension.js:54:8
  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:266:38
  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:478:32
  async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:786:24
  async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:792:48
  _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:827:20
  async*init@resource:///org/gnome/shell/ui/extensionSystem.js:76:14
  _initializeUI@resource:///org/gnome/shell/ui/main.js:303:22
  start@resource:///org/gnome/shell/ui/main.js:175:11
  @resource:///org/gnome/shell/ui/init.js:12:47
  @resource:///org/gnome/shell/ui/init.js:21:20